# Generated by Django 2.2.4 on 2019-11-07 06:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='info1',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='info2',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
