# Generated by Django 2.2.4 on 2019-11-07 06:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191107_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='info1',
            field=otree.db.models.StringField(choices=[['Choice1', 'Choice1'], ['Choice2', 'Choice2']], max_length=10000, null=True, verbose_name='This is an example of the first question?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='info2',
            field=otree.db.models.StringField(choices=[['Choice1', 'Choice1'], ['Choice2', 'Choice2']], max_length=10000, null=True, verbose_name='Second question?'),
        ),
    ]
